### PR TITLE
Package.json and exports

### PR DESCRIPTION
**Pull request by wesleytodd**
New PR with both things necessary for use with browserify.  Closing #13

### CODE REVIEW

**Comment by wesleytodd** [comment]
@SGulseth & @hoppula My intention with that was to not break existing code that is using it on the global namespace.  But if no one thinks that is worth it I could totally remove that from this PR.

**Comment by yoyurec** [comment]
+1 to merge it

>seems like no one cares to use or maintain this library

any ideas about switching to other events microlib? )

**Comment by ccampbell** [comment]
Sorry.  I have definitely been slacking in terms of staying up to date with things.  Believe me, it is not intentional.

This change is so inoffensive.  I will be happy to merge it.  @wesleytodd can you update the formatting here tho?  It looks like you are using tabs and not spaces or at least something in the github diff looks off.

**Comment by wesleytodd** [comment]
Pushed!

**Comment by yoyurec** [comment]
:+1:

**Comment by yoyurec** [comment]
@ccampbell, will you push package to NPM?
https://docs.npmjs.com/getting-started/publishing-npm-packages

After this PR it's totally ready! :metal:

**Comment by rubennorte** [comment]
+1! Any news on this?

**Comment by ccampbell** [comment]
@yoyurec @rubennorte is it considered an okay practice to publish a browser js module to npm that has no server side purpose?  I have other packages there, but they are all designed to run with node.

**Comment by wesleytodd** [comment]
Yes, it is just fine.  They both recommend it and have purposely re-branded to not be "Node Package Manager".  See the header of npmjs.org :)

**Comment by ccampbell** [comment]
Awesome thanks... published

https://www.npmjs.com/package/gator

**Pull request merged**
